#!/usr/bin/env bash

grepprg=rg
if !command -v "$grepprg" &>/dev/null; then
    echo "Cannot find 'rg', fallback to grep" >&2
    grepprg=grep
fi

list_projects() {
    fd . $HOME -d 1 -t d
    fd . $HOME/root -d 1 -t d
    fd . $HOME/root/work $HOME/root/play -d 1 -t d
    fd . $HOME/root/play/labs $HOME/root/play/codingchallenges.fyi -d 2 -t d
}

# list_remote_projects() {
# local vm_home=$(ssh vm 'echo $HOME')
# ssh vm "fd . $vm_home/projects/work $vm_home/projects/play -d 1 -t d; \
#     fd . $vm_home/projects/play/labs $vm_home/projects/play/codingchallenges.fyi -d 2 -t d"
# echo "$vm_home/.ssh"
# echo "$vm_home/.aws"
# echo "$vm_home/.ssh_keys"
# }

find_and_open_projects() {
    projects=$(list_projects)
    # remote_projects=$(list_remote_projects)

    # Add a prefix to remote projects to distinguish them
    # remote_projects_with_prefix=$(echo "$remote_projects" | sed 's/^/vm: /')

    # Combine both lists
    # all_projects=$(echo -e "${projects}\n${remote_projects_with_prefix}")

    # Choose a project with fzf
    selected=$(echo "$projects" | fzf)

    if [ -z "$selected" ]; then
        echo "Empty selection, exiting loop"
        exit 1
    fi

    selected_basename=$(basename "$selected")
    aerospace_window_id=$(aerospace list-windows --all | $grepprg -w Zed | $grepprg -w "$selected_basename —" | head -n 1 | awk '{print $1}')
    # Example command output looks like
    # ❯ aerospace list-windows --all | rg -w Zed | rg -w aincrad
    # 5277 | Zed       | aincrad — e
    # 5302 | Zed       | .dotfiles-private — config

    # If Zed window already exists, focus it
    if [[ $? == 0 ]] && [[ -n "$aerospace_window_id" ]]; then
        # NOTE: This command is slow, aerospace doesn't provide a way to tell if
        # $aerospace_window_id is focused currently so that we can avoid
        # running this command every time
        aerospace focus --window-id $aerospace_window_id
    else
        # Check if it's a remote project
        if [[ $selected == vm:* ]]; then
            # Extract the actual path by removing the "vm: " prefix
            remote_path=${selected#vm: }
            # Use zed with ssh:// protocol
            zed "ssh://vm$remote_path"
        else
            # Local project
            zed "$selected"
        fi
    fi
}

find_and_open_projects
