#!/usr/bin/env bash

grepprg=rg
if !command -v "$grepprg" &>/dev/null; then
    echo "Cannot find 'rg', fallback to grep" >&2
    grepprg=grep
fi

list_projects() {
    find $HOME -maxdepth 1 -type d
    find $HOME/root -maxdepth 1 -type d
    find $HOME/root/work -maxdepth 1 -type d
}

list_remote_projects() {
    ssh orb "$HOME/root/play -maxdepth 1 -type d; \
    find $HOME/root/play/labs $HOME/root/play/codingchallenges.fyi -maxdepth 2 -type d"
}

find_and_open_projects() {
    projects=$(list_projects)
    remote_projects=$(list_remote_projects)

    # Add a prefix to remote projects to distinguish them
    remote_projects_with_prefix=$(echo "$remote_projects" | sed 's/^/orb: /')
    # Combine both lists
    all_projects=$(echo -e "${projects}\n${remote_projects_with_prefix}")

    # Choose a project with fzf
    selected=$(echo "$all_projects" | fzf)

    if [ -z "$selected" ]; then
        echo "Empty selection, exiting loop"
        exit 1
    fi

    selected_basename=$(basename "$selected")
    aerospace_window_id=$(aerospace list-windows --all | $grepprg -w Zed | $grepprg -w "$selected_basename —" | head -n 1 | awk '{print $1}')
    # Example command output looks like
    # ❯ aerospace list-windows --all | rg -w Zed | rg -w aincrad
    # 5277 | Zed       | aincrad — e
    # 5302 | Zed       | .dotfiles-private — config

    # If Zed window already exists, focus it
    if [[ $? == 0 ]] && [[ -n "$aerospace_window_id" ]]; then
        # NOTE: This command is slow, aerospace doesn't provide a way to tell if
        # $aerospace_window_id is focused currently so that we can avoid
        # running this command every time
        aerospace focus --window-id $aerospace_window_id
    else
        # Check if it's a remote project
        if [[ $selected == orb:* ]]; then
            # Extract the actual path by removing the "orb: " prefix
            remote_path=${selected#orb: }
            # Use zed with ssh:// protocol
            zed "ssh://orb$remote_path"
        else
            # Local project
            zed "$selected"
        fi
    fi
}

find_and_open_projects
